name: Benchmark
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'
jobs:
  Compare:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.26.x'
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Build And Install C++ Library
        run: |
          cmake --version
          cd ${{github.workspace}}
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          ls
      - name: Run Benchmark
        run: |
          export LD_LIBRARY_PATH=/home/runner/work/lib:$LD_LIBRARY_PATH
          set -o pipefail; go test ./... -benchmem -run=^$ -bench . | tee output.txt
      - name: Get Previous Benchmark Results
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Save Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: output.txt
          github-token: ${{ secrets.BENCHMARK_TOKEN }}
          benchmark-data-dir-path: 'benchmarks'
          fail-on-alert: true
          comment-on-alert: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          # Enable Job Summary for PRs - deactivated because of issues
          summary-always: ${{ github.event_name != 'push' && github.event_name != 'workflow_dispatch' }}
          #auto-push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          save-data-file: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}